name: Deploy Pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod

    strategy:
      matrix:
        include:
         - context: ./client
           tags: natlachaman/multi-client

         - context: ./server
           image: natlachaman/multi-server

         - context: ./nginx
           image: natlachaman/multi-nginx

         - context: ./worker
           image: natlachaman/multi-worker

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build & test client docker dev image
        run: docker build -t natlachaman/react-test -f ./client/Dockerfile.dev ./client
        run: docker run -e CI=true natlachaman/react-test npm test -- --coverage

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # name: Build multiple docker prod images
      # - run: docker build -t natlachaman/multi-client ./client
      # - run: docker build -t natlachaman/multi-nginx ./nginx
      # - run: docker build -t natlachaman/multi-server ./server
      # - run: docker build -t natlachaman/multi-worker ./worker

      # name: Push to DockerHub
      # - run: docker push natlachaman/multi-client
      # - run: docker push natlachaman/multi-client
      # - run: docker push natlachaman/multi-client
      # - run: docker push natlachaman/multi-client


      - name: Build & Push images
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          # Without load: true, the resulting image is not loaded into docker, and thus not
          # accessible for pushing later on
          load: true
          push: true
          tags: ${{ matrix.tags }}:latest
          cache-to: type=local,src=/tmp/.buildx-cache
          cache-from: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-react
      #     environment_name: Dockerreact-env
      #     existing_bucket_name: elasticbeanstalk-eu-central-1-642447626057
      #     region: eu-central-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip